blogApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'blogApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^[?]page=[1-9][0-9]*', views.index, name='index'),
    url(r'^post/(?P<post_pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<cate_pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<tag_pk>[0-9]+)/$', views.tags, name='tags'),
    url(r'^author/(?P<user_pk>[0-9]+)/$', views.author, name='author'),
    url(r'^about/$', views.about, name='about'),
    url(r'^timeline/$', views.timeline, name='timeline'),
]

usersApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'usersApp'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_confirm/', views.register_confirm, name='register_confirm'),
    url(r'^register/done/$', views.register_done, name='register_done'),
]

blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    """分类数据库"""
    name = models.CharField(max_length=100, verbose_name="分类名")

    class Meta():
        verbose_name = verbose_name_plural = "文章分类"

    def __str__(self):
        return self.name


class Tag(models.Model):
    """标签数据库"""
    name = models.CharField(max_length=100, verbose_name="标签名")

    class Meta():
        verbose_name = verbose_name_plural = "文章标签"

    def __str__(self):
        return self.name


class Post(models.Model):
    """文章数据库"""
    title = models.CharField(max_length=70, verbose_name="标题")
    body = RichTextUploadingField(verbose_name="正文")
    created_time = models.DateTimeField(verbose_name="创建时间")
    modified_time = models.DateTimeField(auto_now_add=True, verbose_name="修改时间")
    excerpt = models.CharField(max_length=200, blank=True, verbose_name="摘要")
    views = models.PositiveIntegerField(default=0, verbose_name="阅读量")
    # 外键约束
    category = models.ForeignKey(Category,null=True, blank=True, on_delete=models.SET_NULL, verbose_name="分类")
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="标签")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="作者")

    class Meta():
        ordering = ['-created_time']
        verbose_name = verbose_name_plural = "文章"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """解析视图对应的URL，并用对象pk替换正则匹配的post_pk部分"""
        return reverse('blogApp:detail', kwargs={'post_pk': self.pk})

    def increase_views(self):
        """访问一次文章页面，自动增加一次"""
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        """重写save方法"""
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:140]
        super(Post, self).save(*args, **kwargs)

commentApp/models.py
from django.db import models
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import TreeForeignKey, MPTTModel


class Comment(MPTTModel):
    """评论信息数据库"""
    username = models.CharField(max_length=150, verbose_name='用户名')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    content = RichTextUploadingField(config_name='user', verbose_name="评论内容")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name="评论的用户")
    post = models.ForeignKey(settings.COMMENT_BIND_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name='评论的文章')
    parent = TreeForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父级评论')

    class MPTTMeta:
        order_insertion_by = ['created_time']
        verbose_name = verbose_name_plural = "用户评论"

    def __str__(self):
        if self.parent is not None:
            return "%s 回复 %s" % (self.username, self.parent.username)
        return "%s 评论文章: %s" % (self.username, self.post.title)

blogApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from commentApp.forms import CommentForm
from .models import Post, Category, Tag


def index(request):
    """首页"""
    post_list = Post.objects.all()
    context_data = paging_index(request, post_list)
    context = context_data
    return render(request, 'blogApp/index.html', context)


def detail(request, post_pk):
    """文章详情页"""
    post = get_object_or_404(Post, pk=post_pk)
    # post.body = markdown.markdown(post.body, ['extra', 'codehilite', 'toc'])
    # post.body = markdownify(post.body)

    # 获得这篇文章下的所有评论集合
    comment_set = post.comment_set.all().order_by('-created_time')

    # 引入"comment"数据模型的表单类的实例
    form = CommentForm()

    # 访问文章，阅读数+1
    post.increase_views()

    context = {'post': post,
               'comment_set': comment_set,
               'form': form,
               }
    return render(request, 'blogApp/detail.html', context)


def archives(request, year, month):
    """按归档日期显示文章"""
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month)
    context_data = paging_index(request, post_list)

    context = context_data
    return render(request, 'blogApp/index.html', context)


def category(request, cate_pk):
    """根据分类显示文章"""
    cate = get_object_or_404(Category, pk=cate_pk)
    post_list = Post.objects.filter(category=cate)
    context_data = paging_index(request, post_list)

    context = context_data
    return render(request, 'blogApp/index.html', context)


def tags(request, tag_pk):
    """根据标签显示文章"""
    t = get_object_or_404(Tag, pk=tag_pk)
    post_list = Post.objects.filter(tag=t)
    context_data = paging_index(request, post_list)

    context = context_data
    return render(request, 'blogApp/index.html', context)


def author(request, user_pk):
    """根据作者显示文章"""
    user = get_object_or_404(User, pk=user_pk)
    post_list = Post.objects.filter(author=user)
    context_data = paging_index(request, post_list)

    context = context_data
    return render(request, 'blogApp/index.html', context)


def about(request):
    context = {}
    return render(request, 'blogApp/about.html', context)


def timeline(request):
    year = Post.objects.dates('created_time', 'year', order='DESC')
    month = Post.objects.dates('created_time', 'month', order='DESC')
    post_list = Post.objects.all()
    context = {'year': year,
               'month': month,
               'post_list': post_list,
               }
    return render(request, 'blogApp/timeline.html', context)


def paging_index(request, post_list):
    """
    * 实现 index页面内的分页效果
    * 效果如： 1 .. 2 3 4 5 6 7 8 .. 100
    """
    per_page_size = 5
    paginator = Paginator(post_list, per_page_size)  # 每页显示的文章数量

    # 文章总数少于每页显示的文章数量，则不分页
    if paginator.count <= per_page_size:
        context_data = {'post_list': post_list}
        return context_data

    page_number = int(request.GET.get('page', 1))  # 用 GET 获取当前请求页码，默认为第一页

    left = []  # 当前页左侧连续页码号
    right = []  # 当前页右侧连续页码号
    left_show_more = False  # 第1页页码号后面是否显示省略号
    right_show_more = False  # 最后一页页码号前面是否显示省略号
    first_page = False  # 是否显示第1页页码号，如果 left 中包含 1，则不显示
    last_page = False  # 是否显示最后一页页码号，如果 right 中包含最后一页的页码，则不显示

    total_pages = paginator.num_pages  # 分页后的总页数
    page_range = paginator.page_range  # 获取分页后所有页码组成的列表，如 [1, 2, 3, 4, 5]

    if page_number == 1:
        # 请求第1页，则 left 连续页码号不需要页码列表，因此默认 left = []
        # right 需要页码列表，如 right = [2, 3, 4]
        # + 3 可改，已显示更多页码，就算超出总页数，也不会报错，只会取到列表最后一位，同 [page_number:-1]
        right = page_range[page_number:page_number + 3]

        if right[-1] < total_pages - 1:
            # 如果"右侧连续页码号"最后一位页码比"分页后总页数"减 1 后还要小，说明他们之间还有其他页，需要显示省略号
            right_show_more = True
        if right[-1] < total_pages:
            # 如果 right 最后一位比"总页数"小，则需要显示最后一页
            last_page = True

    elif page_number == total_pages:
        # 如果请求最后一页，则 right 就不需要页码列表，因此默认 right = []
        # left 需要页码列表，如 left = [2, 3, 4]
        # -4 可改，获取了最后一页前连续的 3 个页码，不足 3 页，则从第一页开始
        left = page_range[(page_number - 4) if (page_number - 4) > 0 else 0:page_number - 1]

        if left[0] > 2:
            # 如果 left 最左边页码比第二页要大，说明他们之间还有其他页，需要显示省略号
            left_show_more = True

        if left[0] > 1:
            # 如果 left 最左边页码比第一页要大，说明 left 不包含第一页，需要显示第一页
            first_page = True

    else:
        # 如果请求的非第一页和最后一页，则 left 和 right 都需要页码列表
        left = page_range[(page_number - 4) if (page_number - 4) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 3]

        if left[0] > 2:
            left_show_more = True
        if left[0] > 1:
            first_page = True

        if right[-1] < total_pages - 1:
            right_show_more = True
        if right[-1] < total_pages:
            last_page = True

    try:
        post_list = paginator.page(page_number)  # 获取请求页内容
    except PageNotAnInteger:
        post_list = paginator.page(1)  # 请求页非整数，则显示第一页
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)  # 请求页超出了最大的页数，则显示最后一页

    context_data = {'left': left,
                    'right': right,
                    'left_show_more': left_show_more,
                    'right_show_more': right_show_more,
                    'first_page': first_page,
                    'last_page': last_page,
                    'post_list': post_list,
                    }
    return context_data


def page_not_found(request):
    return render(request, '404.html')

templates/blogApp/about.html
{% extends 'blogApp/base.html' %}
{% load staticfiles %}

{#{% block background-bubble-js %}#}
{#    <script src="{% static 'blogApp/js/background-bubble.js' %}"></script>#}
{#    <script src="{% static 'blogApp/js/quietflow.min.js' %}"></script>#}
{#{% endblock %}#}

{% block navbar %}
    <li><a class="" href="/">首页<span class="sr-only">(current)</span></a></li>
    <li><a class="" href="{% url 'blogApp:timeline' %}">时间线</a></li>
    <li><a class="navbar-active-a" href="{% url 'blogApp:about' %}">关于</a></li>
{% endblock navbar %}

{% block main %}
    <div class="article-wrap">
        <div class="about-me">
            <blockquote contenteditable="true">
                <img class="img-shadow img-thumbnail" src="{% static 'blogApp/img/saber.jpg' %}" alt="saber">
                <p>
                    本站为个人博客，主要用于记录和分享知识。
                </p>
                <small>
                    steins.gate_@outlook.com
                    <cite title="联系方式"></cite>
                </small>
            </blockquote>
        </div>
    </div>


{% endblock main %}

templates/blogApp/base.html
{% load staticfiles %}
{% load blogApp_tags %}

<!DOCTYPE html>
<html>
<head>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}HuaJi Blog{% endblock %}</title>

    <!-- favicon.ico -->
    <link rel="shortcut icon" href="{% static 'blogApp/img/favicon.ico' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- 代码高亮 -->
    <link rel="stylesheet" href="{% static 'blogApp/css/prism.css' %}">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'blogApp/css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'commentApp/css/comment_list.css' %}">

    <!-- JQuery -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

    <!-- Bootstrap js -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- 代码高亮 -->
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
{#    <script src="{% static 'blogApp/js/prism.js' %}"></script>#}

    <!-- custom js -->
    <script src="{% static 'blogApp/js/blog.js' %}"></script>

    {% block background-bubble-js %}
    {% endblock %}

</head>


<body>

<div class="nav-wrap">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="color: #fff; font-weight: 500; font-size: 19px">Huaji</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% block navbar %}

                        <li><a class="navbar-active-a" href="/">首页<span class="sr-only">(current)</span></a></li>
                        <li><a class="" href="{% url 'blogApp:timeline' %}">时间线</a></li>
                        <li><a class="" href="{% url 'blogApp:about' %}">关于</a></li>

                    {% endblock navbar %}

                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></li>
                                <li><a href="{% url 'logout' %}?next={{ request.path }}">注销</a></li>
                            </ul>
                            {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
                        <li><a href="{% url 'usersApp:register' %}?next={{ request.path }}">注册</a></li>
                    {% endif %}

                </ul>

                <form class="navbar-form navbar-right" method="get" action="{% url 'haystack_search' %}">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control nav-input-search" name="q" placeholder="Search"
                                   required>
                            <span class="input-group-btn">
                            <button type="submit" class="btn btn-success nav-btn-search">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                        </div>
                    </div>
                </form>
            </div><!-- collapse -->
        </div><!-- container -->
    </nav>
</div>

{#<div class="jumbotron">#}
{#    <div class="container">#}
{#        <section>#}
{#            <h2>Welcome</h2>#}
{#        </section>#}
{#        <section>#}
{#            <p></p>#}
{#        </section>#}
{#    </div>#}
{#</div>#}

<div class="container min-height">
    <div class="row">
        <main class="main-content col-md-8 clearfix">
            {% block main %}
            {% endblock main %}
        </main>

        {#        <div class="col-md-1 blank-background"></div>#}


        <div class="col-md-4">
            {% block toc %}
            {% endblock toc %}


            <div class="widget new-article">
                <h3>新发布</h3>
                {% get_recent_post as recent_post_list %}
                <ul>
                    {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}
                                <span class="label label-news">New</span></a>
                        </li>
                    {% empty %}
                        <li>没有新文章</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="widget article-archives" id="toc">
                <h3>归档</h3>
                {% get_archives as date_list %}
                <ul>
                    {% for date in date_list %}
                        <li>
                            <a href="{% url 'blogApp:archives' date.year date.month %}">{{ date.year }}
                                年 {{ date.month }} 月</a>
                        </li>
                    {% empty %}
                        <li>暂时没有归档数据</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="widget article-category">
                <h3>分类</h3>
                {% get_category as category_list %}
                <ul>
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'blogApp:category' category.pk %}">{{ category.name }}
                                <span class="post-count">&nbsp;{{ category.count_posts }}</span></a>
                        </li>
                    {% empty %}
                        <li>暂时没有分类数据</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="widget article-tag">
                <h3>标签</h3>
                {% get_tags as tag_list %}
                <ul>
                    {% for tag in tag_list %}
                        <li>
                            <a class="label label-tag" href="{% url 'blogApp:tags' tag.pk %}">{{ tag.name }}</a>
                        </li>
                    {% empty %}
                        <li>无标签</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="rss">

            </div>
        </div>
    </div>
</div>


<footer>
    <div class="container">
        <ul>
            <li><a href="https://github.com/KaerMorhenXD">Github</a></li>
            <li><a href="{% url 'RSS' %}">Rss</a></li>
            <li></li>
            <li></li>
        </ul>
        <p>© 2018 Copyright. Made with &nbsp;<span class="glyphicon glyphicon-fire" style="color: #fff"></span>&nbsp;Huaji
            blog
        </p>
    </div>
</footer>


<div class="back-to-top btn btn-md" id="back-to-top" title="回到顶部">
    <span class="glyphicon glyphicon-menu-up"></span></div>


</body>
</html>

templates/blogApp/detail.html
{% extends 'blogApp/base.html' %}

{% block main %}
    <article class="detail-article">
        <header>
            <h1 class="detail-article-title">{{ post.title }}</h1>
            <br>
            <div class="detail-article-meta">
                <span class="detail-article-category">
                    <a href="{% url 'blogApp:category' post.category.pk %}" title="点击查找该分类下的文章">{{ post.category }}&nbsp;&nbsp;&nbsp;&nbsp;</a>
                </span>
                <span class="detail-article-time pull-right">
                    <time class="detail-article-time" datetime="{{ post.created_time }}">{{ post.created_time.year }}&nbsp;年&nbsp;{{ post.created_time.month }}&nbsp;月&nbsp;</time></span>
                <span class="comments-link"><a href="#comment-area"
                                               title="点击跳转到评论区"><span class="glyphicon glyphicon-comment"></span>&nbsp;{{ comment_set|length }}&nbsp;&nbsp;&nbsp;</a></span>
                <span class="views-count"><span class="glyphicon glyphicon-fire"></span>&nbsp;{{ post.views }}&nbsp;&nbsp;</span>
            </div>
        </header>

        <div class="article-content clearfix">
            {{ post.body|safe }}
        </div>

        <div class="article-footer">
            <span class="detail-article-author pull-right">
                    <a href="{% url 'blogApp:author' post.author.pk %}" title="点击查找作者的其他文章"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ post.author }}</a>
            </span>
        </div>
    </article>

    <div class="comment-area clearfix" id="comment-area">
        {% include 'commentApp/comment_form.html' with post=post %}
        {% include 'commentApp/comment_list.html' with post=post %}
    </div>
{% endblock main %}

{#{% block toc %}#}
{#    <div class="widget article-content">#}
{#        <h3>目录</h3>#}
{#        {{ post.toc|safe }}#}
{#    </div>#}
{#{% endblock toc %}#}

templates/blogApp/index.html
{% extends 'blogApp/base.html' %}
{% load staticfiles %}

{#{% block background-bubble-js %}#}
{#    <script src="{% static 'blogApp/js/background-bubble.js' %}"></script>#}
{#    <script src="{% static 'blogApp/js/quietflow.min.js' %}"></script>#}
{#{% endblock %}#}

{% block main %}
    <div class="article-wrap">
        {% for post in post_list %}
            <article class="article article-{{ post.pk }}">
                <h2 class="article-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <div class="article-category">
                    <a href="{% url 'blogApp:category' post.category.pk %}">
                        {{ post.category.name }}</a></div>
                <div class="article-excerpt">
                    <p>{{ post.excerpt }}</p></div>
                <div class="article-footer">
                    <span><span class="glyphicon glyphicon-time"></span>
                        &nbsp;{{ post.created_time.year }}年
                        {{ post.created_time.month }}月
                        {{ post.created_time.day }}日&nbsp;&nbsp;</span>
                    <span><span class="glyphicon glyphicon-comment"></span>
                        &nbsp;{{ post.comment_set.count }}&nbsp;&nbsp;</span>
                    <span><span class="glyphicon glyphicon-eye-open"></span>
                        &nbsp;{{ post.views }}&nbsp;&nbsp;</span>
{#                    <span><a href="{% url 'blogApp:author' post.author.pk %}">#}
{#                        {{ post.author }}</a></span>#}
                </div>
            </article>
        {% empty %}
            <div class="no-post"><h2>一篇文章也没有！博主删库跑路了！</h2></div>
        {% endfor %}
    </div>

    <!-- 高大上分页效果 -->
    <div class="pagination">
        <ul>
            {% if first_page %}
                <li><a href="?page=1">1</a></li>
            {% endif %}
            {% if left_show_more %}
                <li><a href="">...</a></li>
            {% endif %}
            {% for left_item in left %}
                <li><a href="?page={{ left_item }}">{{ left_item }}</a></li>
            {% endfor %}

            <li class="current"><a class="current-page" href="javascript:">{{ post_list.number }}</a></li>

            {% for right_item in right %}
                <li><a href="?page={{ right_item }}">{{ right_item }}</a></li>
            {% endfor %}
            {% if right_show_more %}
                <li><a href="">...</a></li>
            {% endif %}
            {% if last_page %}
                <li><a href="?page={{ post_list.paginator.num_pages }}">{{ post_list.paginator.num_pages }}</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock main %}

{#    <canvas id="Quietflow" width="1920" height="1080" style="z-index: -1000; position: absolute; top: 0;"></canvas>#}

templates/blogApp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试文章markdown显示</title>
</head>
<body>
{{ post.body | safe }}
</body>
</html>

templates/blogApp/timeline.html
{% extends 'blogApp/base.html' %}
{% load staticfiles %}

{#{% block background-bubble-js %}#}
{#    <script src="{% static 'blogApp/js/background-bubble.js' %}"></script>#}
{#    <script src="{% static 'blogApp/js/quietflow.min.js' %}"></script>#}
{#{% endblock %}#}

{% block navbar %}
    <li><a class="" href="/">首页<span class="sr-only">(current)</span></a></li>
    <li><a class="navbar-active-a" href="{% url 'blogApp:timeline' %}">时间线</a></li>
    <li><a class="" href="{% url 'blogApp:about' %}">关于</a></li>
{% endblock navbar %}


{% block main %}
    <div class="timeline-wrap">
        <ul>
            {% for y in year %}
                <li class="timeline-year">
                    <h2>{{ y.year }}年</h2>
                    <ul>
                        {% for m in month %}
                            {% if m.year == y.year %}
                                <li class="timeline-month">
                                    <h3>{{ m.month }}月</h3>
                                    <ul>
                                        {% for post in post_list %}
                                            {% if post.created_time.year == y.year and post.created_time.month == m.month %}
                                                <li class="timeline-post"><a href="{% url "blogApp:detail" post.pk %}">
                                                    <h4>{{ post }}</h4></a></li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>

                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
            {% empty %}
                <li><h3>时间线变动率尚未达到 1% _(:з)∠)_</h3></li>
            {% endfor %}
        </ul>
    </div>
{% endblock main %}