blogApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'blogApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^[?]page=[1-9][0-9]*', views.index, name='index'),
    url(r'^post/(?P<post_pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<cate_pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<tag_pk>[0-9]+)/$', views.tags, name='tags'),
    url(r'^author/(?P<user_pk>[0-9]+)/$', views.author, name='author'),
    url(r'^about/$', views.about, name='about'),
    url(r'^timeline/$', views.timeline, name='timeline'),
]

commentApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'commentApp'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)', views.submit_comment, name='submit_comment'),
]

commentApp/models.py
from django.db import models
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import TreeForeignKey, MPTTModel


class Comment(MPTTModel):
    """评论信息数据库"""
    username = models.CharField(max_length=150, verbose_name='用户名')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    content = RichTextUploadingField(config_name='user', verbose_name="评论内容")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name="评论的用户")
    post = models.ForeignKey(settings.COMMENT_BIND_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name='评论的文章')
    parent = TreeForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父级评论')

    class MPTTMeta:
        order_insertion_by = ['created_time']
        verbose_name = verbose_name_plural = "用户评论"

    def __str__(self):
        if self.parent is not None:
            return "%s 回复 %s" % (self.username, self.parent.username)
        return "%s 评论文章: %s" % (self.username, self.post.title)

commentApp/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', 'parent', 'post')

commentApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_POST

from .forms import CommentForm


@require_POST
def submit_comment(request, post_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        # print('success valid')
        comment = form.save(commit=False)
        comment.user = request.user
        comment.username = request.user.username
        comment.save()
        new_comment_location = "#c" + str(comment.id)
        json_content = {'msg': 'comment success!',
                        'new_comment_location': new_comment_location,
                        }
        return JsonResponse(json_content)
    json_content = {'msg': 'comment field!'}
    return JsonResponse(json_content)

commentApp/templates/commentApp/comment_form.html
{% load staticfiles %}
{% load commentApp_tags %}


{% create_comment_form post as form %}

{% if request.user.is_authenticated %}
    <h3>发表评论</h3>
    <form class="comment-form clearfix" id="comment-form" action="{% url 'commentApp:submit_comment' post.pk %}"
          method="post">
        {% csrf_token %}
        <div class="comment-user">
            <span class="comment-name">{{ request.user.username }}&nbsp;</span>
            <span id="reply-icon" class="glyphicon glyphicon-share-alt" style="display: none;"></span>
            <span id="reply-to" style="display: none;">&nbsp;回复：
                    <a class="reply-to-name" href="javascript:" style="color: #dc005a"></a></span>
        </div>
        <div class="comment-control" style="overflow: auto">
            {% for field in form %}
                {{ field }}
                {{ field.errors }}
            {% endfor %}
        </div>
        <a class="rkmd-btn ripple-effect btn-lightBlue" id="cancel-reply" style="display: none">取消</a>
        <button type="submit" class="rkmd-btn ripple-effect btn-lightBlue pull-right">发送</button>
    </form>

{% else %}
    <div class="please-login">
        <h2 class="text-center"><a href="{% url 'login' %}?next={{ request.path }}">登录</a>后评论</h2>
    </div>
{% endif %}

<script src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<script>
    /**
     * 1.0 页面加载时执行
     *   1.1 提交新的评论后，页面刷新后滚动到新评论的位置
     *
     * 2.0 页面元素加载完执行
     *   2.1 评论列表中的图片自动缩放
     *   2.2 取消回复，删除sessionStorage里的reply
     *   2.3 点击回复，判断是否登陆，设置 local-session
     *   2.4 ajax 提交评论并绑定对应 post_id，parent_id
     **/


    /**
     * 1.0 页面加载时执行
     **/
    $(window).load(function () {

        if (sessionStorage.getItem('reply')) {
            sessionStorage.removeItem('reply');
        }

        /**
         * 1.1 提交新的评论后，页面刷新后滚动到新评论的位置
         **/
        if (sessionStorage.getItem('already_submit_comment')) {
            var top = $(sessionStorage.getItem('new_comment_location')).offset().top;
            $('body,html').animate({scrollTop: top}, 50);
            window.location.hash = sessionStorage.getItem('new_comment_location');
            sessionStorage.removeItem('already_submit_comment');
        }

    });


    /**
     * 2.0 页面元素加载完执行
     **/
    $(function () {
        /**
         * 2.1 评论列表中的图片自动缩放
         **/
        var w = $(".comment-list").width();
        $(".comment-list img").each(function () {
            var img_w = $(this).width();
            var img_h = $(this).height();
            if (img_w > w) {
                var height = (w * img_h) / img_w;
                $(this).css({"width": w, "height": height});
            }
        });


        /**
         * 2.2 取消回复，删除sessionStorage里的reply
         **/
        $("#cancel-reply").click(function () {
            sessionStorage.removeItem('reply');
            $('#cancel-reply').css({display: 'none'});
            $('#reply-to').css({display: 'none'});
        });

        /**
         * 2.3 点击回复，判断是否登陆，设置 local-session
         **/
        $(".reply-comment").click(function () {
            if ($(this).hasClass('no-login')) {
                alert('登陆后才能回复');
                return false;
            }
            var parent_id = $(this).attr('id');
            sessionStorage.setItem('reply', true);
            sessionStorage.setItem('parent_id', parent_id);
            $('#cancel-reply').css({display: 'inline-block'});
            $('#reply-icon').css({display: 'inline-block'});
            $('#reply-to').css({display: 'inline-block'});
            $(".reply-to-name").text($(this).data('name'));
        });

        /**
         * 2.4 ajax 提交评论并绑定对应 post_id，parent_id
         **/
        $('.comment-form').submit(function (e) {
            e.preventDefault();

            var content = CKEDITOR.instances.id_content.getData(),
                parent_id = $('#id_parent option:selected').val(),
                post = $('#id_post option:selected').val();

            var list = content.replace(/<.*?>/ig, "").replace(/&nbsp;/ig, "").replace(/\s/g, "");
            if (list.length == 0) {
                alert("评论不能为空！");
                {#window.location.reload();#}
                return false;
            }

            if (sessionStorage.getItem('reply')) {
                parent_id = sessionStorage.getItem('parent_id');
                sessionStorage.removeItem('reply');
            }

            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
            });

            $.ajax({
                url: "{% url 'commentApp:submit_comment' post.pk %}",
                type: 'post',
                dataType: 'json',
                data: {
                    'content': content,
                    'parent': parent_id,
                    'post': post
                },
                success: function (json) {
                    sessionStorage.setItem('already_submit_comment', true);
                    sessionStorage.setItem('new_comment_location', json.new_comment_location);
                    window.location.reload();
                },
                fail: function (json) {
                    alert(json.msg)
                }
            });
        });
    });
</script>

commentApp/templates/commentApp/comment_list.html
{% load staticfiles %}
{% load mptt_tags %}
{% load commentApp_tags %}

{% get_comment_set post as nodes %}

<style>


</style>


<div class="container-fluid no-padding">
    <h3>评论区，共 <span>{{ nodes|length }}</span> 条评论</h3>
    <div class="comment-list">
        {% if nodes.count > 0 %}
            {% recursetree nodes %}
                <div class=" {% if node.is_root_node %}comment-root{% else %}comment-leaf{% endif %}"
                     id="c{{ node.id }}">
                    <div class="comment-header clearfix">
                        <span class="comment-name">{{ node.username }}</span>
                        {% if not node.is_root_node %}
                            <span class="glyphicon glyphicon-share-alt"></span>
                            <span class="comment-reply-to">{{ node.parent.username }}</span>
                        {% endif %}
                        <time class="pull-right" datetime="{{ node.created_time }}">
                            &nbsp;{{ node.created_time|timesince }}&nbsp;前&nbsp;
                        </time>
                    </div>

                    <div class="comment-body">
                        {{ node.content|safe }}
                    </div>
                    <div class="comment-footer clearfix">
                        <a class="reply-comment pull-right {% if not request.user.is_authenticated %}no-login{% endif %}"
                           data-name="{{ node.username }}"
                           id="{{ node.id }}" href="#comment-form"
                           style="color: #dc005a;">回复&nbsp;</a>
                    </div>
                </div>
                <div class="comment-children {% if node.is_root_node %}block-level-1{% endif %}">
                    {% if not node.is_leaf_node %}
                        {{ children }}
                    {% endif %}
                </div>
            {% endrecursetree %}
        {% else %}
            <p>还没人评论，不来抢个沙发嘛 _(:з)∠)_</p>
        {% endif %}
    </div>
</div>