blogApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'blogApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^[?]page=[1-9][0-9]*', views.index, name='index'),
    url(r'^post/(?P<post_pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<cate_pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<tag_pk>[0-9]+)/$', views.tags, name='tags'),
    url(r'^author/(?P<user_pk>[0-9]+)/$', views.author, name='author'),
    url(r'^about/$', views.about, name='about'),
    url(r'^timeline/$', views.timeline, name='timeline'),
]

commentApp/models.py
from django.db import models
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import TreeForeignKey, MPTTModel


class Comment(MPTTModel):
    """评论信息数据库"""
    username = models.CharField(max_length=150, verbose_name='用户名')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    content = RichTextUploadingField(config_name='user', verbose_name="评论内容")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name="评论的用户")
    post = models.ForeignKey(settings.COMMENT_BIND_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name='评论的文章')
    parent = TreeForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父级评论')

    class MPTTMeta:
        order_insertion_by = ['created_time']
        verbose_name = verbose_name_plural = "用户评论"

    def __str__(self):
        if self.parent is not None:
            return "%s 回复 %s" % (self.username, self.parent.username)
        return "%s 评论文章: %s" % (self.username, self.post.title)

templates/search/search.html
{% extends 'blogApp/base.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}

            <div class="article-wrap">
                <article class="article article-{{ result.object.pk }}">
                    <h2 class="article-title"><a href="{{ result.object.get_absolute_url }}">
                        {% highlight result.object.title with query html_tag "span" css_class "highlight_me" %}</a>
                    </h2>
                    <div class="article-category">
                        <a href="{% url 'blogApp:category' result.object.category.pk %}">{{ result.object.category.name }}</a>
                    </div>
                    <div class="article-excerpt">
                        <p>{{ result.object.excerpt }}</p></div>
                    <div class="article-content">
                        <p>{% highlight result.object.excerpt with query html_tag "span" css_class "highlight_me" %}...</p>
                    </div>
                    <div class="article-footer">
                        <span>{{ result.object.created_time.year }}年{{ result.object.created_time.month }}月{{ result.object.created_time.day }}日</span>
                        <span> {{ result.object.comment_set.count }}评论</span>
                        {#                    <span> {{ result.object.views }}点击量</span>#}
                        {#                    <span> <a href="{% url 'blogApp:author' result.object.author.pk %}">{{ result.object.author }}</a></span>#}
                    </div>
                </article>
            </div>

        {% empty %}
            <h3>没有搜索到结果！</h3>
        {% endfor %}
        {% if page.has_next or page.has_previous %}
            <nav aria-label="...">
                <ul class="pager">
                    <li>
                        {% if page.has_previous %}
                            <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">Previous
                        {% endif %}
                        {% if page.has_previous %}
                            </a>
                        {% endif %}
                    </li>
                    <li>
                        {% if page.has_next %}
                            <a href="?q={{ query }}&amp;page={{ page.next_page_number }}">Next
                        {% endif %}
                        {% if page.has_next %}
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </nav>

        {% endif %}
    {% else %}
        <h2>还没输入搜索关键词呢 _(:з)∠)_</h2>
    {% endif %}
{% endblock main %}