blogApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'blogApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^[?]page=[1-9][0-9]*', views.index, name='index'),
    url(r'^post/(?P<post_pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<cate_pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<tag_pk>[0-9]+)/$', views.tags, name='tags'),
    url(r'^author/(?P<user_pk>[0-9]+)/$', views.author, name='author'),
    url(r'^about/$', views.about, name='about'),
    url(r'^timeline/$', views.timeline, name='timeline'),
]

usersApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'usersApp'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_confirm/', views.register_confirm, name='register_confirm'),
    url(r'^register/done/$', views.register_done, name='register_done'),
]

usersApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    is_active = models.BooleanField(
        _('active'),
        default=False,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    email = models.EmailField(_('email address'), unique=True)
    nickname = models.CharField(max_length=50, blank=True, verbose_name="昵称")


class Email_Confirmation_Code(models.Model):
    code = models.CharField(max_length=256, verbose_name="确认码")
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="注册用户")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="生成时间")

    def __str__(self):
        return self.user.username + ':' + self.code

    class Meta:
        ordering = ['created_time']
        verbose_name = verbose_name_plural = '邮箱确认码'

usersApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import User


class RegisterForm(UserCreationForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        # help_text=_("Enter the same password as before, for verification."),
    )

    # def clean_email(self):
    #     """
    #     自定义处理表单字段
    #     """
    #     cleaned_data = self.cleaned_data['email']
    #     if len(cleaned_data) < 3:
    #         raise forms.ValidationError("太短了，不是邮箱！")
    #
    #     return None

    class Meta(UserCreationForm.Meta):
        model = User  # 指定的是自定义的用户模型 - usersApp.User
        fields = ('username', 'email')

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

        # labels = {}

        # help_texts = {
        #     'username': _(''),
        # }

        # error_messages = {
        #     'password2': {
        #         'password_entirely_numeric': _("密码不能全为数字。"),
        #     },
        # }
        #
        # field_classes = {}

usersApp/views.py
import datetime
import hashlib

from django.shortcuts import render, redirect
from blogProject import settings

from .forms import RegisterForm
from .models import Email_Confirmation_Code
from .tasks import send_register_mail

REDIRECT_FIELD_NAME = 'next'


def register(request,
             redirect_field_name=REDIRECT_FIELD_NAME):
    """
    用户注册视图

    :param redirect_field_name: 重定向上一个页面 get 参数名
    """
    # get 请求中，next 通过 url 传递 ?next={{ request.path }}
    # post 请求中，next 通过表单传递 <input class="hidden" name="next" value="{{ next }}">
    redirect_to = request.POST.get(redirect_field_name, request.GET.get(redirect_field_name, ''))

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()
            code = make_email_confirm_code(new_user)
            send_register_mail.delay(email=new_user.email, code=code)
            return redirect('usersApp:register_done')
            # if redirect_to:
            #     return redirect('usersApp:register_done')
            # else:
            #     return redirect('/')
    else:
        form = RegisterForm()

    context = {'form': form,
               'next': redirect_to,
               }
    return render(request, 'usersApp/register.html', context)


def register_confirm(request,
                     confirm_days=settings.CONFIRM_DAYS):
    """
    用户注册确认

    :param confirm_days: 注册邮件有效期
    :return:
    """
    code = request.GET.get('code', None)
    try:
        confirm = Email_Confirmation_Code.objects.get(code=code)
    except:
        message = '错误的注册验证信息！'
        return render(request, 'usersApp/register_confirm.html', {'message': message})

    created_time = confirm.created_time
    now = datetime.datetime.now()

    if now > created_time + datetime.timedelta(confirm_days):
        confirm.user.delete()
        message = '邮件过期了，已经失效了！(>_<) 重新注册一下吧'
    else:
        confirm.user.is_active = True
        confirm.user.save()
        confirm.delete()
        message = '注册成功啦，快去登陆吧！_(:з)∠)_'
    return render(request, 'usersApp/register_confirm.html', {'message': message})


def register_done(request):
    return render(request, 'usersApp/register_done.html')


def hash_sha256(key, salt='Huaji'):
    """
    加密

    :param key: 需要加密的关键字段
    :param salt: 给关键字段加点"盐"
    :return: 一个 sha256 加密的哈希值
    """
    sha256 = hashlib.sha256()
    key += salt
    sha256.update(key.encode())  # 需要 bit 类型
    return sha256.hexdigest()


def make_email_confirm_code(user):
    """
    制作注册用户的邮箱确认码
    在邮箱确认码添加关联用户表的数据

    :param user: 注册用户的实例对象
    :return: 关联到用户的确认码
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_sha256(user.username, now)
    Email_Confirmation_Code.objects.create(code=code, user=user)
    return code

templates/usersApp/register.html
{% extends 'usersApp/users_base.html' %}

{% block title %}用户注册{% endblock %}

{% block main %}
    <form class="form-center" action="{% url 'usersApp:register' %}" method="post">
        {% csrf_token %}
        <h2 class="text-center">注册</h2>

        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">用户名:</label>
            {{ form.username }}
{#            {% if form.username.help_text %}#}
{#                <p>{{ form.username.help_text|safe }}</p>#}
{#            {% endif %}#}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">邮箱:</label>
            {{ form.email }}
            {% if form.email.help_text %}
                <p>{{ form.email.help_text|safe }}</p>
            {% endif %}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            <label for="{{ form.password1.id_for_label }}">密码:</label>
            {{ form.password1 }}
            {% if form.password.help_text %}
                <p>{{ form.password.help_text|safe }}</p>
            {% endif %}
            {{ form.password.errors }}
        </div>
        <div class="form-group">
            <label for="{{ form.password2.id_for_label }}">确认密码:</label>
            {{ form.password2 }}
            {% if form.password2.help_text %}
                <p>{{ form.password2.help_text|safe }}</p>
            {% endif %}
            {{ form.password2.errors }}
        </div>

        <button type="submit" class="btn btn-block btn-primary btn-lg">注册</button>

        <!-- 接收 request.path 的 next -->
        <input type="hidden" name="next" value="{{ next }}">
{#        <p class="copyright">© 2018 Copyright. Huaji</p>#}
    </form>
{% endblock main %}

templates/usersApp/register_confirm.html
{% extends 'usersApp/users_base.html' %}

{% block title %}注册确认{% endblock %}

{% block js %}
    <script>
        $(function () {
            /**
             * 2.0 倒计时返回首页
             **/
            var time = 3;
            var timer = setInterval(redirect_index, 1000);

            function redirect_index() {
                var $time_tip = $('#time-tip');
                if (time > 0) {
                    $time_tip.html(time);
                    time--;
                } else {
                    clearInterval(timer);
                    location.href = "{% url 'login' %}";
                }
            }
        })
    </script>
{% endblock js %}

{% block main %}
<div class="form-center">
        <h2 class="text-center">{{ message }}</h2>
        <div class="text-center">
            <h1 id="time-tip">4</h1>
            <p>秒后前往登录页</p>
        </div>
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'login' %}">立即登录</a>
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'blogApp:index' %}">回到首页</a>
    </div>
{% endblock main %}

templates/usersApp/register_done.html
{% extends 'usersApp/users_base.html' %}

{% block title %}等待确认邮件{% endblock %}

{% block js %}
    <script>
        $(function () {
            /**
             * 2.0 倒计时返回首页
             **/
            var time = 6;
            var timer = setInterval(redirect_index, 1000);

            function redirect_index() {
                var $time_tip = $('#time-tip');
                if (time > 0) {
                    $time_tip.html(time);
                    time--;
                } else {
                    clearInterval(timer);
                    location.href = "{% url 'blogApp:index' %}";
                }
            }
        })
    </script>
{% endblock js %}

{% block main %}
<div class="form-center">
        <h2 class="text-center">请前往邮箱确认注册</h2>
        <div class="text-center">
            <h1 id="time-tip">7</h1>
            <p>秒后返回首页</p>
        </div>
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'blogApp:index' %}">立即回到首页</a>
    </div>
{% endblock main %}

templates/usersApp/users_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- favicon.ico -->
    <link rel="shortcut icon" href="{% static 'blogApp/img/favicon.ico' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'usersApp/css/users.css' %}">

    <!-- JQuery -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

    <!-- Bootstrap js -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- js -->
    <script src="{% static 'usersApp/js/users.js' %}"></script>

    {% block js %}
    {% endblock %}
</head>


<body>

{% block main %}
{% endblock main %}

</body>
</html>